---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8063/eureka/
server:
port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: subject
my:
  words: I,You,He,She,It
  
---
spring:
  profiles: verb
my:
  words: ran,knew,had,saw,bought

---
spring:
  profiles: article
my:
  words: a,the

---
spring:
  profiles: adjective
my:
  words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
my:
  words: boat,book,vote,seat,backpack,partition,groundhog
  
