---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8063/eureka/
      
server:
  port: 8065
  
# Allow thymeleaf template changes to reload:
spring:
  thymeleaf:
    cache: false

zuul:
  ignoredServices: "*"
  routes:
    path: /api/users/**
    serviceId: UMA4Rest
    path: /api/instances/**
    serviceId: UMA4Instance
